# Generated by Django 3.1.6 on 2021-02-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Servicio_nombre', models.CharField(max_length=200)),
                ('Servicio_contenido', models.TextField()),
                ('Servicio_publicado', models.DateTimeField(verbose_name='Fecha de Publicación')),
            ],
        ),
    ]
