# Generated by Django 3.1.6 on 2021-02-17 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='Servicio_contenido',
            new_name='servicio_contenido',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='Servicio_nombre',
            new_name='servicio_nombre',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='Servicio_publicado',
            new_name='servicio_publicado',
        ),
    ]
